# Generated by Django 4.0.1 on 2022-01-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=50, unique=True)),
                ('Player_1', models.CharField(default='Player 1', max_length=50)),
                ('Player_2', models.CharField(default='Player 2', max_length=50)),
                ('Last_Played', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row00', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row01', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row02', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row10', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row11', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row12', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row20', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row21', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('row22', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.room')),
            ],
        ),
    ]
